// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {appkit} from '../models';

export function GetAboutInfo():Promise<app.AboutInfo>;

export function GetBooks():Promise<Array<app.Book>>;

export function GetHomeInfo():Promise<app.HomeInfo>;

export function GetInventions():Promise<Array<app.Invention>>;

export function GetLinks():Promise<Array<app.Link>>;

export function GetRealEstate():Promise<Array<app.RealEstate>>;

export function GetSidebarWidth():Promise<number>;

export function GetTab(arg1:string):Promise<string>;

export function GetTableState(arg1:string):Promise<appkit.TableState>;

export function GetTimeline():Promise<Array<app.TimelineEvent>>;

export function SetSidebarWidth(arg1:number):Promise<void>;

export function SetTab(arg1:string,arg2:string):Promise<void>;

export function SetTableState(arg1:string,arg2:appkit.TableState):Promise<void>;
