// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBook(arg1) {
  return window['go']['app']['App']['CreateBook'](arg1);
}

export function CreateInvention(arg1) {
  return window['go']['app']['App']['CreateInvention'](arg1);
}

export function CreateLink(arg1) {
  return window['go']['app']['App']['CreateLink'](arg1);
}

export function CreateRealEstateItem(arg1) {
  return window['go']['app']['App']['CreateRealEstateItem'](arg1);
}

export function CreateTimelineEvent(arg1) {
  return window['go']['app']['App']['CreateTimelineEvent'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['app']['App']['DeleteBook'](arg1);
}

export function DeleteInvention(arg1) {
  return window['go']['app']['App']['DeleteInvention'](arg1);
}

export function DeleteLink(arg1) {
  return window['go']['app']['App']['DeleteLink'](arg1);
}

export function DeleteRealEstateItem(arg1) {
  return window['go']['app']['App']['DeleteRealEstateItem'](arg1);
}

export function DeleteTimelineEvent(arg1) {
  return window['go']['app']['App']['DeleteTimelineEvent'](arg1);
}

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetBook(arg1) {
  return window['go']['app']['App']['GetBook'](arg1);
}

export function GetBooks() {
  return window['go']['app']['App']['GetBooks']();
}

export function GetHomeInfo() {
  return window['go']['app']['App']['GetHomeInfo']();
}

export function GetInvention(arg1) {
  return window['go']['app']['App']['GetInvention'](arg1);
}

export function GetInventionFilterOptions() {
  return window['go']['app']['App']['GetInventionFilterOptions']();
}

export function GetInventions() {
  return window['go']['app']['App']['GetInventions']();
}

export function GetLastRoute() {
  return window['go']['app']['App']['GetLastRoute']();
}

export function GetLink(arg1) {
  return window['go']['app']['App']['GetLink'](arg1);
}

export function GetLinks() {
  return window['go']['app']['App']['GetLinks']();
}

export function GetRealEstateItem(arg1) {
  return window['go']['app']['App']['GetRealEstateItem'](arg1);
}

export function GetRealEstateItems() {
  return window['go']['app']['App']['GetRealEstateItems']();
}

export function GetSidebarWidth() {
  return window['go']['app']['App']['GetSidebarWidth']();
}

export function GetTab(arg1) {
  return window['go']['app']['App']['GetTab'](arg1);
}

export function GetTabRoute(arg1) {
  return window['go']['app']['App']['GetTabRoute'](arg1);
}

export function GetTableState(arg1) {
  return window['go']['app']['App']['GetTableState'](arg1);
}

export function GetTimelineCategories() {
  return window['go']['app']['App']['GetTimelineCategories']();
}

export function GetTimelineEvent(arg1) {
  return window['go']['app']['App']['GetTimelineEvent'](arg1);
}

export function GetTimelineEvents() {
  return window['go']['app']['App']['GetTimelineEvents']();
}

export function SaveLastRoute(arg1) {
  return window['go']['app']['App']['SaveLastRoute'](arg1);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4);
}

export function SetSidebarWidth(arg1) {
  return window['go']['app']['App']['SetSidebarWidth'](arg1);
}

export function SetTab(arg1, arg2) {
  return window['go']['app']['App']['SetTab'](arg1, arg2);
}

export function SetTabRoute(arg1, arg2) {
  return window['go']['app']['App']['SetTabRoute'](arg1, arg2);
}

export function SetTableState(arg1, arg2) {
  return window['go']['app']['App']['SetTableState'](arg1, arg2);
}

export function UpdateBook(arg1) {
  return window['go']['app']['App']['UpdateBook'](arg1);
}

export function UpdateInvention(arg1) {
  return window['go']['app']['App']['UpdateInvention'](arg1);
}

export function UpdateLink(arg1) {
  return window['go']['app']['App']['UpdateLink'](arg1);
}

export function UpdateRealEstateItem(arg1) {
  return window['go']['app']['App']['UpdateRealEstateItem'](arg1);
}

export function UpdateTimelineEvent(arg1) {
  return window['go']['app']['App']['UpdateTimelineEvent'](arg1);
}
