// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {app} from '../models';
import {appkit} from '../models';

export function CreateBook(arg1:db.Book):Promise<db.Book>;

export function CreateInvention(arg1:db.Invention):Promise<db.Invention>;

export function CreateLink(arg1:db.Link):Promise<db.Link>;

export function CreateRealEstateItem(arg1:db.RealEstate):Promise<db.RealEstate>;

export function CreateTimelineEvent(arg1:db.TimelineEvent):Promise<db.TimelineEvent>;

export function DeleteBook(arg1:number):Promise<void>;

export function DeleteInvention(arg1:number):Promise<void>;

export function DeleteLink(arg1:number):Promise<void>;

export function DeleteRealEstateItem(arg1:number):Promise<void>;

export function DeleteTimelineEvent(arg1:number):Promise<void>;

export function GetAboutInfo():Promise<app.AboutInfo>;

export function GetBook(arg1:number):Promise<db.Book>;

export function GetBooks():Promise<Array<db.Book>>;

export function GetHomeInfo():Promise<app.HomeInfo>;

export function GetInvention(arg1:number):Promise<db.Invention>;

export function GetInventionFilterOptions():Promise<db.InventionFilterOptions>;

export function GetInventions():Promise<Array<db.Invention>>;

export function GetLastRoute():Promise<string>;

export function GetLink(arg1:number):Promise<db.Link>;

export function GetLinks():Promise<Array<db.Link>>;

export function GetRealEstateItem(arg1:number):Promise<db.RealEstate>;

export function GetRealEstateItems():Promise<Array<db.RealEstate>>;

export function GetSidebarWidth():Promise<number>;

export function GetTab(arg1:string):Promise<string>;

export function GetTabRoute(arg1:string):Promise<string>;

export function GetTableState(arg1:string):Promise<appkit.TableState>;

export function GetTimelineCategories():Promise<Array<string>>;

export function GetTimelineEvent(arg1:number):Promise<db.TimelineEvent>;

export function GetTimelineEvents():Promise<Array<db.TimelineEvent>>;

export function SaveLastRoute(arg1:string):Promise<void>;

export function SaveWindowGeometry(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetSidebarWidth(arg1:number):Promise<void>;

export function SetTab(arg1:string,arg2:string):Promise<void>;

export function SetTabRoute(arg1:string,arg2:string):Promise<void>;

export function SetTableState(arg1:string,arg2:appkit.TableState):Promise<void>;

export function UpdateBook(arg1:db.Book):Promise<void>;

export function UpdateInvention(arg1:db.Invention):Promise<void>;

export function UpdateLink(arg1:db.Link):Promise<void>;

export function UpdateRealEstateItem(arg1:db.RealEstate):Promise<void>;

export function UpdateTimelineEvent(arg1:db.TimelineEvent):Promise<void>;
