// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetBooks() {
  return window['go']['app']['App']['GetBooks']();
}

export function GetHomeInfo() {
  return window['go']['app']['App']['GetHomeInfo']();
}

export function GetInventions() {
  return window['go']['app']['App']['GetInventions']();
}

export function GetLinks() {
  return window['go']['app']['App']['GetLinks']();
}

export function GetRealEstate() {
  return window['go']['app']['App']['GetRealEstate']();
}

export function GetSidebarWidth() {
  return window['go']['app']['App']['GetSidebarWidth']();
}

export function GetTab(arg1) {
  return window['go']['app']['App']['GetTab'](arg1);
}

export function GetTableState(arg1) {
  return window['go']['app']['App']['GetTableState'](arg1);
}

export function GetTimeline() {
  return window['go']['app']['App']['GetTimeline']();
}

export function SetSidebarWidth(arg1) {
  return window['go']['app']['App']['SetSidebarWidth'](arg1);
}

export function SetTab(arg1, arg2) {
  return window['go']['app']['App']['SetTab'](arg1, arg2);
}

export function SetTableState(arg1, arg2) {
  return window['go']['app']['App']['SetTableState'](arg1, arg2);
}
